language: php
sudo: false
php:
  - 7.0
  - 7.1
  - 7.2
matrix:
  fast_finish: true
before_install:
  - composer self-update --no-progress --no-interaction
install:
  - make deps
script:
  - make test
notifications:
  hipchat:
    rooms:
      secure:
